---
# - name: "Add Node.js from Nodesource"
#   become: true
#   apk:
#     update_cache: true

# - name: "upgrade apk packages"
#   become: true
#   apk:
#     upgrade: yes 

# - name: "remove stale dependencies"
#   become: true 
#   apk: 
#     autoremove: yes 

# - name: "install dependencies [nodejs and npm]"
#   become: true 
#   raw: apk add nodejs

# - name: "Install PM2 Globally"
#   become: true
#   apt:
#     name: pm2
#     global: yes
#     production: yes 
#     state: present

- name: "move env variables to /etc/profile.d/"
  become: true
  copy:
    src: myenv.sh
    dest: /etc/profile.d
