---
- name: "install dependencies [nodejs and npm]"
  become: true 
  raw: apk -y update && apk install -y nodejs && apk install -y npm && apk install pm2 -g

- name: "move env variables to /etc/profile.d/"
  become: true
  copy:
    src: myenv.sh
    dest: /etc/profile.d
